import os

##########################################################################
# Things to build

#TEX files that should become PDF files (via latex)
TEX_FILES = [
    "pitch",
    "buscase",
    "buscase-ieee",
]


##########################################################################
# Setup builders and environment

env = Environment(
    ENV      = os.environ,
)

##########################################################################
# Add builders and dependecies to environment

for base in TEX_FILES:
    pdf = env.PDF(target = base + ".pdf", source = base + ".tex")
